import type { CaseSnapshot, VerdictResult } from "./types";
import { VERDICT_META } from "./types";
import { classLabel, fmtFdaDate } from "./classification";

const RELATION_LABEL: Record<string, string> = {
  same_manufacturer: "Same manufacturer",
  same_ingredient: "Same ingredient",
};

/** Plain-text/Markdown rendering of a finished investigation, for copying out
 * to Slack, email, or a ticket -- the same information the card shows, just
 * in a form that survives leaving the browser. */
export function toMarkdown(result: VerdictResult, caseSnapshot: CaseSnapshot): string {
  const meta = VERDICT_META[result.verdict];
  const lines: string[] = [];

  lines.push(`# ${caseSnapshot.drug_name ?? result.recall_number}`);
  lines.push("");
  const headerBits = [
    caseSnapshot.firm,
    caseSnapshot.classification ? classLabel(caseSnapshot.classification) : null,
    caseSnapshot.date ? fmtFdaDate(caseSnapshot.date) : null,
    result.recall_number,
  ].filter(Boolean);
  lines.push(headerBits.join(" · "));
  lines.push("");
  lines.push(`**Verdict: ${meta.label.toUpperCase()}** — ${meta.description}`);
  lines.push("");

  if (result.recommended_action) {
    lines.push(`**Recommended action:** ${result.recommended_action}`);
    lines.push("");
  }

  if (result.summary) {
    lines.push("## Summary");
    lines.push(result.summary);
    lines.push("");
  }

  if (result.evidence.length > 0) {
    lines.push("## Supporting findings");
    for (const item of result.evidence) lines.push(`- ${item}`);
    lines.push("");
  }

  if (result.related_products.length > 0) {
    lines.push("## Related products to watch");
    for (const p of result.related_products) {
      lines.push(`- **${p.name}** (${p.manufacturer}) — ${RELATION_LABEL[p.relation] ?? p.relation}: ${p.reason}`);
    }
    lines.push("");
  }

  if (result.open_questions.length > 0) {
    lines.push("## Limitations");
    for (const item of result.open_questions) lines.push(`- ${item}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by Recall Investigator · data: openFDA drug enforcement & adverse event APIs_");

  return lines.join("\n");
}
